# Generated by Django 2.1.4 on 2018-12-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iam', models.CharField(max_length=15, verbose_name='IAM number')),
                ('alias', models.CharField(max_length=50, verbose_name='Account alias')),
                ('passwd', models.CharField(max_length=15, verbose_name='Password')),
            ],
        ),
    ]
