# Generated by Django 2.1.4 on 2018-12-27 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='account',
        ),
    ]
