# Generated by Django 2.1.4 on 2018-12-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20181227_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='alias',
            field=models.CharField(max_length=50, verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='account',
            name='passwd',
            field=models.CharField(max_length=15, verbose_name='Secret Key'),
        ),
    ]
