# Generated by Django 2.1.4 on 2019-01-02 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20190102_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='iam',
            field=models.CharField(max_length=15, verbose_name='Region of IAM'),
        ),
    ]
